#!/bin/sh
IMG=$(readlink -f $1)
CPT=0
colors -n 16 -p < $IMG | while read HEXCODE; do
        printf '*color%d: %s\n' "$CPT" "$HEXCODE"
        CPT=$(expr $CPT + 1)
done | xrdb -merge
xrdb -query colors > ~/.Xresources
feh --bg-fill $IMG && cp $IMG $(dirname $IMG)/wp.png
